import '../../api/languages/methods.js';
import '../../api/interns/methods.js';
import '../../api/interns/server/publications.js';
//import '../../api/departments/departments.js';
import '../../api/departments/server/publications.js';
import '../../api/stages/common.js';
import '../../api/stages/server/publications.js';
import '../../api/users/methods.js';
import '../../api/users/server/publications.js';
